// editor/src/lib/codaro/ui/separator/Separator.svelte
<script lang="ts">
  import { cn } from "../utils";

  type Props = {
    class?: string;
    orientation?: "horizontal" | "vertical";
    decorative?: boolean;
  };

  let { class: className, orientation = "horizontal", decorative = true }: Props = $props();
</script>

<div
  role={decorative ? "none" : "separator"}
  aria-orientation={decorative ? undefined : orientation}
  class={cn(
    "bg-border-subtle shrink-0",
    orientation === "horizontal" ? "h-px w-full" : "w-px h-full",
    className,
  )}
></div>

// productFrontend/src/components/ui/separator.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

type SeparatorProps = React.HTMLAttributes<HTMLDivElement> & {
  orientation?: "horizontal" | "vertical";
};

function Separator({ className, orientation = "horizontal", ...props }: SeparatorProps) {
  return (
    <div
      data-slot="separator"
      role="separator"
      aria-orientation={orientation}
      className={cn(
        "shrink-0 bg-border",
        orientation === "horizontal" ? "h-px w-full" : "h-full w-px",
        className,
      )}
      {...props}
    />
  );
}

export { Separator };
